## File generated by the BNF Converter (bnfc 2.9.4.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Probnetkat/Test

# Rules for building the parser.

Probnetkat/Abs.hs Probnetkat/Lex.x Probnetkat/Par.y Probnetkat/Print.hs Probnetkat/Test.hs : probnetkat.bnf
	bnfc --haskell -d probnetkat.bnf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Probnetkat/Test : Probnetkat/Abs.hs Probnetkat/Lex.hs Probnetkat/Par.hs Probnetkat/Print.hs Probnetkat/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Probnetkat/*.hi Probnetkat/*.o Probnetkat/*.log Probnetkat/*.aux Probnetkat/*.dvi

distclean : clean
	-rm -f Probnetkat/Abs.hs Probnetkat/Abs.hs.bak Probnetkat/ComposOp.hs Probnetkat/ComposOp.hs.bak Probnetkat/Doc.txt Probnetkat/Doc.txt.bak Probnetkat/ErrM.hs Probnetkat/ErrM.hs.bak Probnetkat/Layout.hs Probnetkat/Layout.hs.bak Probnetkat/Lex.x Probnetkat/Lex.x.bak Probnetkat/Par.y Probnetkat/Par.y.bak Probnetkat/Print.hs Probnetkat/Print.hs.bak Probnetkat/Skel.hs Probnetkat/Skel.hs.bak Probnetkat/Test.hs Probnetkat/Test.hs.bak Probnetkat/XML.hs Probnetkat/XML.hs.bak Probnetkat/AST.agda Probnetkat/AST.agda.bak Probnetkat/Parser.agda Probnetkat/Parser.agda.bak Probnetkat/IOLib.agda Probnetkat/IOLib.agda.bak Probnetkat/Main.agda Probnetkat/Main.agda.bak Probnetkat/probnetkat.dtd Probnetkat/probnetkat.dtd.bak Probnetkat/Test Probnetkat/Lex.hs Probnetkat/Par.hs Probnetkat/Par.info Probnetkat/ParData.hs Makefile
	-rmdir -p Probnetkat/

# EOF
