name: probnetkat
version: 0.1.0.0
github: "githubuser/probnetkat"
license: BSD3
author: "Floyd Remmerswaal"
maintainer: "floydremmerswaal@gmail.com"
copyright: "2023 Floyd Remmerswaal"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - src/Syntax/Lex.x
  - src/Syntax/Par.y

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/probnetkat#readme>

dependencies:
  - base >= 4.7 && < 5
  - monad-bayes >= 1.1.0
  - log-domain >= 0.13.2
  - monad-extras >= 0.6.0
  - containers >= 0.6.5.1
  - array
  - containers
  - pretty-tree
  - fgl
  - fgl-visualize >= 0.1.0.1

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  probnetkat-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - probnetkat
    build-tools:
      - alex
      - happy

tests:
  probnetkat-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - probnetkat
      - hspec
