entrypoints Exp;

EAss. Exp2 ::= Ident "<-" Integer;
ETest. Exp2 ::= Ident "=" Integer;
EDup. Exp2 ::= "dup";
ESkip. Exp2 ::= "skip";
EDrop. Exp2 ::= "drop";


EProb. Exp ::= Exp "+["Double"]" Exp;
ESeq. Exp ::= Exp ";" Exp;
Epar. Exp ::= Exp "&" Exp;

coercions Exp 4;