-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- | The abstract syntax of language Syntax.

module Syntax.Abs where

import Prelude (Double, Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp
    = EAssSw Integer
    | EAssPt Integer
    | ESwEq Integer
    | EPtEq Integer
    | EDup
    | ESkip
    | EDrop
    | ESeq Exp Exp
    | EProbD Exp Exp
    | EProb Exp Double Exp
    | EPar Exp Exp
    | EKleene Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

