-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Syntax.Abs

import Control.Arrow

import Control.Monad.Bayes.Class

import Semantics 

type Err = Either String
type Result m = Err (Kleisli m SH SH)

failure :: Show a => a -> Result m
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Syntax.Abs.Ident -> Result m
transIdent x = case x of
  Syntax.Abs.Ident string -> failure x