entrypoints Exp;

EAss. Exp3 ::= Ident "<-" Integer;
ETest. Exp3 ::= Ident "=" Integer;
EDup. Exp3 ::= "dup";
ESkip. Exp3 ::= "skip";
EDrop. Exp3 ::= "drop";

ESeq. Exp2 ::= Exp2 ";" Exp3;
EProb. Exp1 ::= Exp1 "+[" Double "]" Exp2;
Epar. Exp ::= Exp "&" Exp1;


coercions Exp 3;

comment "//" ;
comment "/*" "*/" ;